<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php

    if($_SESSION['user']){
        echo 'Hola '.$_SESSION['user']->getUsername().'. <a href="index.php?c=user&logout=1">Salir</a><br><br>';
    }

foreach($movies as $movie){
    echo "- <a href='index.php?c=movie&id=".$movie->getId()."'>".$movie->getTitle()."</a><br>";
}
?>
</body>
</html>