<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
    if($info){
        echo "<script> alert('".$info."')</script>";
    }

    else{
        echo "<h1>".$movie->getTitle()."</h1>";
        echo "año de estreno: ".$movie->getYear()."<br>";
        echo "director: ".$movie->getDirector()."<br>";
    }
    ?>

    <a href="index.php">Volver</a>
</body>
</html>